// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCb2hmpu8RTk-xEb549VykWpGecqh2qYg',
    appId: '1:296812497101:web:022019dcc18eba46b1c184',
    messagingSenderId: '296812497101',
    projectId: 'clone-f2005',
    authDomain: 'clone-f2005.firebaseapp.com',
    storageBucket: 'clone-f2005.firebasestorage.app',
    measurementId: 'G-1EWKBEVV76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpkEaiim07AWuYAz3StTx8GH3Fw3bXF4',
    appId: '1:296812497101:android:3c0f24b26cd088efb1c184',
    messagingSenderId: '296812497101',
    projectId: 'clone-f2005',
    storageBucket: 'clone-f2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlZMjG3o7JHZFyoL4GKPAlY2jBUp15_nU',
    appId: '1:296812497101:ios:fd02e32ad8ee7b66b1c184',
    messagingSenderId: '296812497101',
    projectId: 'clone-f2005',
    storageBucket: 'clone-f2005.firebasestorage.app',
    iosBundleId: 'com.example.ytClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlZMjG3o7JHZFyoL4GKPAlY2jBUp15_nU',
    appId: '1:296812497101:ios:fd02e32ad8ee7b66b1c184',
    messagingSenderId: '296812497101',
    projectId: 'clone-f2005',
    storageBucket: 'clone-f2005.firebasestorage.app',
    iosBundleId: 'com.example.ytClone',
  );
}
